# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem 'sinatra'        # Lightweight web framework
gem 'puma'           # Web server for Sinatra
gem 'mongo'          # MongoDB driver for Ruby
gem 'pg'             # PostgreSQL adapter for ActiveRecord
gem 'dotenv'         # For managing environment variables
gem "rackup", "~> 2.2"  # Rack-based server for Sinatra
gem 'jwt'            # JSON Web Token implementation
gem 'bcrypt'         # Password hashing library
gem 'json'           # JSON parsing and generation
gem 'net-http'       # HTTP library for making requests
gem 'activerecord'   # ORM for connecting to PostgreSQL database
gem 'rack-cors'      # Middleware for Cross-Origin Resource Sharing

