services:
  auth-service:
    image: bfury0329/auth-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:1997Zanahoria@database-1.cpexyh7ws48q.us-east-2.rds.amazonaws.com:5432/postgres
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - SECRET_KEY=mysecretkey
    networks:
      microservices-network:
        ipv4_address: 192.168.100.2

  catalog-service:
    image: bfury0329/catalog-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - SECRET_KEY=mysecretkey
    networks:
      microservices-network:
        ipv4_address: 192.168.100.3

  session-service:
    image: bfury0329/session-service
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - PORT=5004
    networks:
      microservices-network:
        ipv4_address: 192.168.100.4

  interface-service:
    image: bfury0329/interface-service
    ports:
      - "8080:8080"
    networks:
      microservices-network:
        ipv4_address: 192.168.100.5

  user-service:
    image: bfury0329/user-service
    ports:
      - "5002:5002"
    environment:
      - POSTGRESQL_HOST=database-1.cpexyh7ws48q.us-east-2.rds.amazonaws.com
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=1997Zanahoria
    networks:
      microservices-network:
        ipv4_address: 192.168.100.6

networks:
  microservices-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"