version: "3.8"

services:
  auth-service:
    image: bfury0329/auth-service
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - SQLALCHEMY_TRACK_MODIFICATIONS=true
      - SECRET_KEY=mysecretkey
    networks:
      - microservices-network

  catalog-service:
    image: bfury0329/catalog-service
    build: ./catalog-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - SECRET_KEY=mysecretkey
    networks:
      - microservices-network

  session-service:
    image: bfury0329/session-service
    build: ./session-service
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - PORT=5004
    networks:
      - microservices-network

  interface-service:
    image: bfury0329/interface-service
    build: ./interface-service
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
      - CATALOG_SERVICE_URL=http://catalog-service:5003
      - SESSION_SERVICE_URL=http://session-service:5004
      - USER_SERVICE_URL=http://user-service:5002
      - SEARCH_SERVICE_URL=http://search-service:5005
      - ORDERS_SERVICE_URL=http://orders-service:5008
      - RECOMMENDATION_SERVICE_URL=http://recommendation-service:5006
      - CUSTOM_SERVICE_URL=http://custom-service:5007
      - CHAT_SERVICE_URL=http://chat-service:5010
    networks:
      - microservices-network

  user-service:
    image: bfury0329/user-service
    build: ./user-service
    ports:
      - "5002:5002"
    environment:
      - POSTGRESQL_HOST=aws-0-us-west-1.pooler.supabase.com
      - POSTGRESQL_PORT=6543
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USER=postgres.imfqyzgimtercyyqeqof
      - POSTGRESQL_PASSWORD=1997Guallaba
    networks:
      - microservices-network

  search-service:
    image: bfury0329/search-service
    build: ./search-service
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - ELASTICSEARCH_URI=http://elasticsearch:9200
    networks:
      - microservices-network

  recommendation-service:
    image: bfury0329/recommendation-service
    build: ./recommendation-service
    ports:
      - "5006:5006"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - microservices-network

  customization-service:
    image: bfury0329/custom-service
    build: ./custom-service
    ports:
      - "5007:5007"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - POSTGRES_URI=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - AUTH_SERVICE_URL=http://auth-service:5001
    networks:
      - microservices-network

  orders-service:
    image: bfury0329/orders-service
    build: ./orders-service
    ports:
      - "5008:5008"
    environment:
      - POSTGRES_URI=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - CATALOG_URL=http://catalog-service:5003/models/id/
    networks:
      - microservices-network

  chat-service:
    image: bfury0329/chat-service
    build: ./chat-service
    ports:
      - "5010:5010"
    environment:
      - POSTGRES_URI=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
    networks:
      - microservices-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - catalog-service
      - session-service
      - interface-service
      - user-service
      - search-service
    networks:
      - microservices-network

  # Servicio de Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - microservices-network

  # Servicio de Redis
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge