services:
  auth-service:
    image: bfury0329/auth-service:latest
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - SQLALCHEMY_TRACK_MODIFICATIONS=true
      - SECRET_KEY=mysecretkey
    networks:
      - microservices-network

  catalog-service:
    image: bfury0329/catalog-service:latest
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - SECRET_KEY=mysecretkey
    networks:
      - microservices-network

  session-service:
    image: bfury0329/session-service:latest
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - PORT=5004
    networks:
      - microservices-network

  interface-service:
    image: bfury0329/interface-service:latest
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
      - CATALOG_SERVICE_URL=http://catalog-service:5003
      - SESSION_SERVICE_URL=http://session-service:5004
      - USER_SERVICE_URL=http://user-service:5002
      - SEARCH_SERVICE_URL=http://search-service:5005  
    networks:
      - microservices-network

  user-service:
    image: bfury0329/user-service:latest
    ports:
      - "5002:5002"
    environment:
      - POSTGRESQL_HOST=aws-0-us-west-1.pooler.supabase.com
      - POSTGRESQL_PORT=6543
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USER=postgres.imfqyzgimtercyyqeqof
      - POSTGRESQL_PASSWORD=1997Guallaba
    networks:
      - microservices-network

  search-service:
    image: bfury0329/search-service:latest
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - ELASTICSEARCH_URI=http://localhost:9200
    networks:
      - microservices-network

  chat-service:
    image: bfury0329/chat-service
    ports:
      - "5010:5010"
    environment:
      - POSTGRES_URI=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
    networks:
      - microservices-network  

  orders-service:
    image: bfury0329/orders-service
    ports:
      - "5008:5008"
    environment:
      - POSTGRES_URI=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - CATALOG_URL=http://catalog-service:5003/models/id/
    networks:
      - microservices-network
    
  custom-service:
    image: bfury0329/custom-service
    ports:
      - "5007:5007"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - POSTGRES_URI=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - AUTH_SERVICE_URL=http://auth-service:5001
    networks:
      - microservices-network

  recommendation-service:
    image: bfury0329/recommendation-service
    ports:
      - "5006:5006"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - microservices-network
  

  

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - catalog-service
      - session-service
      - interface-service
      - user-service
      - search-service  
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge