networks:
  microservices-network:
services:
  auth-service:
    image: bfury0329/auth-service
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres.imfqyzgimtercyyqeqof:1997Guallaba@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - SQLALCHEMY_TRACK_MODIFICATIONS=true
      - SECRET_KEY=mysecretkey
    networks:
      - microservices-network

  session-service:
    image: bfury0329/session-service
    build: ./session-service
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb+srv://MicroserviceDev:1997999@cluster0.hdqpd.mongodb.net/CatalogServiceDB?retryWrites=true&w=majority
      - PORT=5004
    networks:
      - microservices-network

  user-service:
    image: bfury0329/user-service
    build: ./user-service
    ports:
      - "5002:5002"
    environment:
      - POSTGRESQL_HOST=aws-0-us-west-1.pooler.supabase.com
      - POSTGRESQL_PORT=6543
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USER=postgres.imfqyzgimtercyyqeqof
      - POSTGRESQL_PASSWORD=1997Guallaba
    networks:
      - microservices-network